### ISSUE TITLE
[VR] The PDF pages are not turned

### ISSUE THREAD

**Issue by Softvision-RemusDranca** [mozilla/hubs#4951]
**[Affected Versions]:**
- Oculus Browser

**[Affected Platforms]:**
- Oculus Quest

**[Prerequisites]:**
- Your Hubs Cloud stack is set up.
- Have a room opened.

**[Steps to reproduce]:**
1. Import a PDF file into the room.
2. Change the PDF pages and observe the behavior.

**[Expected results]:**
- The pages are turned.

**[Actual results]:**
- The pages number is changed but the file remains on the same page.

**[Notes]:**
- This issue is reproducible when trying to change to the previous or next page.

**Comment by vincentfretin** [comment]
FYI the exact same issue I believe was reported to A-Frame repo https://github.com/aframevr/aframe/issues/4984
And #4181 may be related to this too.

**Comment by vincentfretin** [comment]
#3968 may be related to this issue.

**Comment by Renji3** [comment]
It seems that this is caused by functions added to window.requestAnimationFrame not beeing called anymore because the window is not redrawn in vr.
The PR [#5427](https://github.com/mozilla/hubs/pull/5427) should fix this

**Comment by emclaren** [comment]
If we can implement a fix to this fairly quickly we should do this as P1, we may downgrade this to P2 if it requires a deeper dive.

**Comment by Dayk0** [comment]
Hello, this bug is really annoying because PDFs are widely used for VR. Is there any news concerning the progress of the correction of this bug?

**Comment by YasienKashef** [comment]
I will add myself into this thread because this bug is still as February 2023 present. In Hubs Cloud as well as the official Mozilla Hubs instances have this bug. It happens also on all VR devices so it doesnt depend which VR device is used.

I hope this bug fix will be taken faster in consideration as multiple clients as well as users cant use the PDF tool, which is very important especially if its used for introduction to the virtual room itself as well as to display controls and usability.
So most users are still hanging on the very first steps in the experience.

**Comment by CodingBitsDev** [comment]
The proposed fix above solves the problem. 
It is currently uses aframe systems but that can be easily adapted to bitECS.

**Comment by PlumCantaloupe** [comment]
> It seems that this is caused by functions added to window.requestAnimationFrame not beeing called anymore because the window is not redrawn in vr.
> This is however used by PDFjs to render the pdfs and resolve the page.render() promise in src/components/media-pdf.js
> The PR [#5427](https://github.com/mozilla/hubs/pull/5427) proposes a possible solution.

Thank you! This helped me on a similar project. I very much appreciate the share 🙏

**Comment by DougReeder** [comment]
For reference, A-Frame decided that this issue was something to be handled in PDF.js, not A-Frame:  https://github.com/aframevr/aframe/issues/4984

**Comment by vincentfretin** [comment]
Of course that's nothing to do with aframe core, but you can't do a fix in pdf.js either, the lib doesn't know about the xrSession, so you still need to call xrSession.requestAnimationFrame externally via an aframe component or something else that you use today on hubs.

**Comment by vincentfretin** [comment]
To clarify, I assume the fix is calling xrSession.requestAnimationFrame instead of window.requestAnimationFrame to properly rerender the canvas texture. I didn't look at the pdf.js code, and I didn't review #5427 or tested any fix myself.

**Comment by Exairnous** [comment]
This should be fixed now with the merge of https://github.com/Hubs-Foundation/hubs/pull/6575 but let us know if it reappears.
