### ISSUE TITLE
Hello,We want to use a Korean nickname

### ISSUE THREAD

**Issue by KWAK1221** [mozilla/hubs#5462]
**Is your feature request related to a problem? Please describe.**
We're building a metaverse platform using the hubs cloud.Currently, only English is allowed for the nicknames of the users, but we want Korean to be allowed as well. I don't know if I can customize or not to allow Korean.

**Describe the solution you'd like**
I want to use a nickname in Korean.

**Describe alternatives you've considered**

**Additional context**

**Comment by rawnsley** [comment]
A recent change to text rendering makes this much easier to implement, but it requires Reticulum changes, which are outside of the supported Hubs Cloud. See also https://github.com/mozilla/hubs/issues/3934

**Comment by wsxiaoys** [comment]
I've implemented this in my client earlier this week (https://github.com/mozilla/hubs/pull/5463/files).

The only pitfall is jsonschema version in hubs is stale thus not support RegExp construction with unicode flag, thus causing the schema validation failed when a CJK name is used.

**Comment by rawnsley** [comment]
> I've implemented this in my client earlier this week (https://github.com/mozilla/hubs/pull/5463/files).
> 
> The only pitfall is jsonschema version in hubs is stale thus not support RegExp construction with unicode flag, thus causing the schema validation failed when a CJK name is used.

Very nice! Do you have any problems with reticulum rejecting names? Maybe it is only room names that go through a RegEx in the backend.

It's possible we can dump all the RegEx checks now in both client and server. Do they still have a purpose?

**Comment by albirrkarim** [comment]
> I've implemented this in my client earlier this week (https://github.com/mozilla/hubs/pull/5463/files).
> 
> The only pitfall is jsonschema version in hubs is stale (no support of RegExp construction with unicode flag), thus causing the schema validation failed when a CJK name is used.

Can you share live project URL ? @wsxiaoys

**Comment by juunini** [comment]
Hello, I'll guide this issue.

1. You must set `fontUrl.default` in `troika-text.js`
    - https://github.com/belivvr/hubs/blob/113dfa307e8f75376860ccccb5ca4e9b09e14864/src/components/troika-text.js#L65
2. Find `a-z` and add `가-힣` in regexp

then you can use korean name.

**Comment by rawnsley** [comment]
> Hello, I'll guide this issue.
> 
> 1. You must set `fontUrl.default` in `troika-text.js`
>    
>    * https://github.com/belivvr/hubs/blob/113dfa307e8f75376860ccccb5ca4e9b09e14864/src/components/troika-text.js#L65
> 2. Find `a-z` and add `가-힣` in regexp
> 
> then you can use korean name.

You will also need to add `https://cdn.jsdelivr.net` to the _Extra Content Security Policy connect-src Rules_ section of your Hubs Cloud server settings.

This works well for supporting ASCII characters and the Korean alphabet, but it doesn't support extended latin characters (Sofía) or Chinese characters (张伟). What we really need is [font fallback support](https://github.com/mozilla/hubs/issues/3934#issuecomment-1156164314).

**Comment by juunini** [comment]
reticulum config `connect-src` to add font url
